// <auto-generated />
namespace StandingsTable.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _3rdmigrati : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3rdmigrati));
        
        string IMigrationMetadata.Id
        {
            get { return "202111112232154_3rd migrati"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
